# Generated by Django 3.2 on 2021-05-04 20:22

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210504_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=profiles.models.profile_image_file_path),
        ),
    ]
