# Generated by Django 3.2 on 2021-05-04 20:29

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', null=True, upload_to=profiles.models.profile_image_file_path),
        ),
    ]
